<a href="https://colab.research.google.com/github/abhishek1998s/NLP-Projects/blob/main/Spam_and_Ham_using_BOW_%26_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
   from google.colab import files
   files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"abhishekkumarsing98","key":"29c918c7768663d8c05a412380371615"}'}

In [2]:
   !mkdir -p ~/.kaggle
   !cp kaggle.json ~/.kaggle/
   !chmod 600 ~/.kaggle/kaggle.json

In [3]:
   !kaggle datasets download -d bagavathypriya/spam-ham-dataset

Dataset URL: https://www.kaggle.com/datasets/bagavathypriya/spam-ham-dataset
License(s): unknown
100% 207k/207k [00:00<00:00, 538kB/s]
100% 207k/207k [00:00<00:00, 537kB/s]


In [4]:
   !unzip spam-ham-dataset.zip

Archive:  spam-ham-dataset.zip
  inflating: spamhamdata.csv         


In [5]:
import pandas as pd
message = pd.read_csv('spamhamdata.csv', sep='\t',names=["label","message"])
message.sample(10)

label                                            message
5389   ham               Ok.ok ok..then..whats ur todays plan
5324   ham  Dear Sir,Salam Alaikkum.Pride and Pleasure mee...
883    ham  I love to give massages. I use lots of baby oi...
4491   ham  My computer just fried the only essential part...
5419   ham  I'm at bruce &amp; fowler now but I'm in my mo...
1186   ham                                 Annoying isn't it.
1932   ham                What pa tell me.. I went to bath:-)
1222   ham                             Prakesh is there know.
198    ham  is your hamster dead? Hey so tmr i meet you at...
4045   ham                              Yes, my reg is  Ciao!

In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [7]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

**Stemming and Lemmatization**

In [8]:
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [9]:
corpus=[]
for i in range(0,len(message)):
  #removing non letter character
  review=re.sub('[^a-zA-Z]',' ',message['message'][i])
  #lowercase
  review=review.lower()
  #spliting the words
  review=review.split()
  #applying stemming and removing stopwords
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # Apply lemmatization
  review = [lemmatizer.lemmatize(word) for word in review]
  # Join words back into a single string
  review = ' '.join(review)
  # Append to corpus
  corpus.append(review)

In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

**Creating bag of words**

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
#x is independent feature
x=cv.fit_transform(corpus).toarray()

In [16]:
cv.vocabulary_

{'go': 820,
 'point': 1611,
 'crazi': 464,
 'avail': 123,
 'bugi': 243,
 'great': 868,
 'world': 2431,
 'la': 1094,
 'cine': 353,
 'got': 859,
 'wat': 2342,
 'ok': 1478,
 'lar': 1107,
 'joke': 1059,
 'wif': 2397,
 'oni': 1496,
 'free': 734,
 'entri': 627,
 'wkli': 2421,
 'comp': 413,
 'win': 2402,
 'fa': 671,
 'cup': 477,
 'final': 701,
 'tkt': 2135,
 'st': 1967,
 'may': 1276,
 'text': 2084,
 'receiv': 1707,
 'question': 1676,
 'std': 1980,
 'txt': 2206,
 'rate': 1688,
 'appli': 87,
 'free entri': 739,
 'entri wkli': 629,
 'cup final': 478,
 'std txt': 1981,
 'txt rate': 2215,
 'rate appli': 1689,
 'dun': 587,
 'say': 1803,
 'earli': 593,
 'alreadi': 55,
 'nah': 1391,
 'think': 2106,
 'goe': 839,
 'usf': 2276,
 'live': 1175,
 'around': 99,
 'though': 2114,
 'freemsg': 746,
 'hey': 928,
 'darl': 496,
 'week': 2365,
 'word': 2427,
 'back': 140,
 'like': 1160,
 'fun': 762,
 'still': 1983,
 'tb': 2061,
 'xxx': 2464,
 'send': 1832,
 'even': 640,
 'brother': 233,
 'speak': 1951,
 'treat': 21

In [18]:
y=pd.get_dummies(message['label'])
y=y.iloc[:,1].values
y

array([False, False,  True, ..., False, False, False])

In [19]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [20]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(x_train,y_train)

In [22]:
y_pred=spam_detect_model.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9865470852017937

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[967,   8],
       [  7, 133]])

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       975
        True       0.94      0.95      0.95       140

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**Creating TF-IDF and NGgram**

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
 tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
 x=tfidf.fit_transform(corpus).toarray()

In [29]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g" % x))

In [30]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [31]:
tfidf.vocabulary_

{'go': 820,
 'point': 1611,
 'crazi': 464,
 'avail': 123,
 'bugi': 243,
 'great': 868,
 'world': 2431,
 'la': 1094,
 'cine': 353,
 'got': 859,
 'wat': 2342,
 'ok': 1478,
 'lar': 1107,
 'joke': 1059,
 'wif': 2397,
 'oni': 1496,
 'free': 734,
 'entri': 627,
 'wkli': 2421,
 'comp': 413,
 'win': 2402,
 'fa': 671,
 'cup': 477,
 'final': 701,
 'tkt': 2135,
 'st': 1967,
 'may': 1276,
 'text': 2084,
 'receiv': 1707,
 'question': 1676,
 'std': 1980,
 'txt': 2206,
 'rate': 1688,
 'appli': 87,
 'free entri': 739,
 'entri wkli': 629,
 'cup final': 478,
 'std txt': 1981,
 'txt rate': 2215,
 'rate appli': 1689,
 'dun': 587,
 'say': 1803,
 'earli': 593,
 'alreadi': 55,
 'nah': 1391,
 'think': 2106,
 'goe': 839,
 'usf': 2276,
 'live': 1175,
 'around': 99,
 'though': 2114,
 'freemsg': 746,
 'hey': 928,
 'darl': 496,
 'week': 2365,
 'word': 2427,
 'back': 140,
 'like': 1160,
 'fun': 762,
 'still': 1983,
 'tb': 2061,
 'xxx': 2464,
 'send': 1832,
 'even': 640,
 'brother': 233,
 'speak': 1951,
 'treat': 21

In [32]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [34]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model=MultinomialNB().fit(x_train,y_train)

In [35]:
y_pred=spam_tfidf_model.predict(x_test)

In [37]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9847533632286996

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[983,   1],
       [ 16, 115]])

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      1.00      0.99       984
        True       0.99      0.88      0.93       131

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

